# Generated by Django 4.2.7 on 2023-12-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="record", name="deleted_at",),
        migrations.RemoveField(model_name="record", name="updated_at",),
    ]
