# Generated by Django 4.2.7 on 2023-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_record_deleted_at_remove_record_updated_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="record", name="name",),
    ]
