# Generated by Django 4.2.7 on 2023-12-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_category_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="brand",),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.RemoveField(model_name="product", name="featured_image",),
    ]
