# Generated by Django 4.2.7 on 2023-12-05 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_subcategory_category_subcategory_categories"),
        ("products", "0003_remove_product_brand_remove_product_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_location",
                        to="products.locationcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location_code_prefix", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(name="Category",),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default="Others",
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.subcategory",
            ),
        ),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="User",),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="to_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_location",
                to="products.locationcode",
            ),
        ),
        migrations.AddField(
            model_name="locationcode",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.store"
            ),
        ),
    ]
