# Generated by Django 4.2.7 on 2023-12-05 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_subcategory_category_subcategory_categories"),
        ("products", "0004_locationcode_stockmovement_store_delete_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.subcategory",
            ),
        ),
    ]
