# Generated by Django 4.2.7 on 2023-12-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="subcategory",),
    ]
